### ISSUE TITLE
Option to select nodes and have the base class and pathing to them optimized

### ISSUE THREAD

**Issue by GamerGoddessDin** [brather1ng/PoESkillTree#1]
Basically what I'm looking for is to be able to select the important nodes for a build and (possibly) "equip" the "end game" gear the build is intended to use and have the program then find the most efficient pathing to a class start and all of the selected nodes while meeting the prerequisites for the equipped gear and gems (possibly disregarding level requirements).

Is this a function that is already implemented in this branch, or at least a function that is intended to be implemented in the future?

**Comment by brather1ng** [comment]
First, this is just my fork, so you probably want to post this issue to the original repository, where the discussion and development happens (https://github.com/EmmittJ/PoESkillTree/issues).
This fork doesn't has any features the main repository does not have, at least only until they are finished enough to get pulled. I activated Issues here for some reason, I should probably deactivate them again :)

Your idea is partly possible atm. You can use the "Skill tagged nodes" feature (in the "Tools" submenu) to skill the selected nodes (tag nodes with right click). This, however, only searches for the current class and doesn't take into account anything else besides minimizing the points spent.

The part with meeting the prerequisites for gear and gems is something not possible atm, but in the long term is planned for the skill tree optimizer I am implementing (see https://github.com/EmmittJ/PoESkillTree/issues/106).
However, automatically selecting a class is not planned for that atm and I don't know if there is good way to do it. But I might do that too since it sound useful.
