### ISSUE TITLE
GridView cell editing 

### ISSUE THREAD

**Issue by MLanghof** [brather1ng/PoESkillTree#4]
- WPF makes the use of DataGrid mandatory (instead of DataGridView)
- There's no inbuilt functionality in DataGrid to support going directly into edit mode when a cell is selected.

I've tried a few of the suggested workarounds, all revolving around manually giving the cell Focus() (on mouse down or similar). However, there's also an IsEditing property, which seems to be closer to what we need.

Current state is setting the IsEditing property on mouseEnter to true and on mouseLeave to false. The issue seems to be that it wants to apply editing to the non-edit version of the cell, while subsequent user input will transfer it into the "real" edit mode. And it has a ton of other issues, as expected for trying to circumvent stuff in this way...

**Comment by brather1ng** [comment]
I don't know if that is exactly what you had in mind, but http://wpf.codeplex.com/wikipage?title=Single-Click%20Editing&ProjectName=wpf works without any functional problems and feels much better than the default.

The simplified version of it that still works:
```
        private void DataGridCell_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            var cell = sender as DataGridCell;
            if (cell != null && !cell.IsEditing && !cell.IsReadOnly)
            {
                if (!cell.IsFocused)
                {
                    cell.Focus();
                }
                // DataGrid.SelectionUnit must not be "FullRow"
                cell.IsSelected = true;
            }
        }
```
So it seems Focus() and IsSelected together is the proper way of changing to edit mode. Setting IsEditing instead breaks everything.

**Comment by MLanghof** [comment]
I've seen that and tried it, but giving the cell focus and selecting it resulted (for me at least) in the blue selection highlight, which I thought was really ugly.

**Comment by brather1ng** [comment]
Yeah, I changed it to only select single cells, that way it is still not looking particularly good, but way less ugly.
I guess stuff like that happens if you use MahApps, which restyles most stuff, and then try to style stuff yourself.

**Comment by brather1ng** [comment]
What do you think about how I've done the DataGrid for the pseudo attributes? To me that feels more intuitive and is also way less buggy with the remove button and validation things.

It still doesn't go into edit mode automatically, but that isn't needed that much because adding rows is done differently. One click instead of two click edit mode could be done the same way as I've done it for the attribute DataGrid.

**Comment by MLanghof** [comment]
I'll look into it when I next have time for it!

**Comment by brather1ng** [comment]
Well, since there is no need for adding new items directly via the DataGrid, there is a pretty easy solution for what you had in mind: Simply making the normal CellTemplates editable and not using any CellEditingTemplates makes the cells editable without going into "edit mode", see 53e187914ae14b68cad36f6f402ea057ecd7972c.

Since that solves the issue, I'll close this. But you are still free to look into it :)
